%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\sebas\OneDrive\Allt annat\Dokument\Programmering\Kandidatarbete\LCAQMP\Korrektionsvärden CO2.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 18-Mar-2022 12:58:28

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 10);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:J3";

% Specify column names and types
opts.VariableNames = ["UNIT1", "UNIT2", "UNIT3", "UNIT4", "UNIT5", "UNIT6", "UNIT7", "UNIT8", "UNIT9", "UNIT10"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char", "char", "char", "char"];

% Specify variable properties
opts = setvaropts(opts, ["UNIT1", "UNIT2", "UNIT3", "UNIT4", "UNIT5", "UNIT6", "UNIT7", "UNIT8", "UNIT9", "UNIT10"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["UNIT1", "UNIT2", "UNIT3", "UNIT4", "UNIT5", "UNIT6", "UNIT7", "UNIT8", "UNIT9", "UNIT10"], "EmptyFieldRule", "auto");

% Import the data
KorrektionsvrdenCO1 = readtable("C:\Users\sebas\OneDrive\Allt annat\Dokument\Programmering\Kandidatarbete\LCAQMP\Korrektionsvärden CO2.xlsx", opts, 'ReadVariableNames', true);

% %% Convert to output type
% KorrektionsvrdenCO1 = table2cell(KorrektionsvrdenCO1);
% numIdx = cellfun(@(x) ~isnan(str2double(x)), KorrektionsvrdenCO1);
% KorrektionsvrdenCO1(numIdx) = cellfun(@(x) {str2double(x)}, KorrektionsvrdenCO1(numIdx));
% 
% %% Clear temporary variables
% clear opts